from .index import *
from .instructor_home import *
from .tutor_views import *
from .verifier import *
from .login import *
from .comment import *
from .profile import *
from .ujuzi import *
from .guest_auth import *
