# Generated by Django 3.2.9 on 2022-08-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UJUZI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
