# Generated by Django 3.2.9 on 2022-08-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UJUZI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='CategoryIcon/%Y/%m/%d', verbose_name='Category Icon'),
        ),
    ]
