# Generated by Django 3.2.9 on 2022-08-17 13:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UJUZI', '0004_remove_user_is_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalContentViewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today, editable=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UJUZI.module', unique=True)),
            ],
            options={
                'verbose_name': 'Total Content Viewers',
                'verbose_name_plural': 'Total Content Viewers',
            },
        ),
        migrations.CreateModel(
            name='ContentViewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, editable=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UJUZI.module')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Viewers',
                'verbose_name_plural': 'Content Viewers',
                'unique_together': {('content', 'viewer', 'date')},
            },
        ),
    ]
