# Generated by Django 3.2.9 on 2022-08-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UJUZI', '0005_contentviewers_totalcontentviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalcontentviewers',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UJUZI.module'),
        ),
    ]
